/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CtlPet;
import clases.clsCat;
import clases.clsDog;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author mayko
 */
public class frmPet extends javax.swing.JFrame {
    CtlPet ctlpet = new CtlPet();
    LinkedList<clsDog> dogObjectList = new LinkedList<>();
    LinkedList<clsCat> catObjectList = new LinkedList<>();

    /**
     * Creates new form frmPet
     */
    public frmPet() {
        initComponents();
    }
    
    private void FillJlist(){
        DefaultListModel model = new  DefaultListModel();
        int index = 0;
        for (clsDog dog : dogObjectList) {
            String data = dog.getName() + " " + dog.getBreed() + " -Dog " ;
            model.add(index, data);
            index++;
        }
        for (clsCat cat : catObjectList) 
        {
            String DataCat = cat.getName() + " " + cat.getBreed() + " -Cat ";
            model.add(index, DataCat);
            index++;
            
        }
        petList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        petList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCatCode = new javax.swing.JTextField();
        txtCatBornYear = new javax.swing.JTextField();
        txtCatName = new javax.swing.JTextField();
        txtCatColor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboCatHealthStatus = new javax.swing.JComboBox<>();
        comboCatBreed = new javax.swing.JComboBox<>();
        btnCatCreate = new javax.swing.JButton();
        btnCatSearch = new javax.swing.JButton();
        btnCatEdit = new javax.swing.JButton();
        btnCatRemove = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnDogCreate = new javax.swing.JButton();
        btnDogSearch = new javax.swing.JButton();
        btnDogEdit = new javax.swing.JButton();
        btnDogRemove = new javax.swing.JButton();
        txtDogCode = new javax.swing.JTextField();
        txtDogBornYear = new javax.swing.JTextField();
        txtDogName = new javax.swing.JTextField();
        txtDogColor = new javax.swing.JTextField();
        comboDogHealthStatus = new javax.swing.JComboBox<>();
        comboDogBreed = new javax.swing.JComboBox<>();
        checkDogPedigree = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        petList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "pet1", "pet2", "pet3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(petList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pet List", jPanel1);

        jLabel2.setText("Code");

        jLabel3.setText("Born Year");

        jLabel4.setText("Name");

        jLabel5.setText("Color");

        txtCatName.setToolTipText("");

        jLabel6.setText("Health Status");

        jLabel7.setText("Breed");

        comboCatHealthStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Healthy", "Sick", "Item 3", "Item 4" }));

        comboCatBreed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Criollo", "Persa", "Item 3", "Item 4" }));

        btnCatCreate.setText("Create");
        btnCatCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatCreateActionPerformed(evt);
            }
        });

        btnCatSearch.setText("Search");
        btnCatSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatSearchActionPerformed(evt);
            }
        });

        btnCatEdit.setText("Edit");
        btnCatEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatEditActionPerformed(evt);
            }
        });

        btnCatRemove.setText("Eliminar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(12, 12, 12)
                                .addComponent(comboCatHealthStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCatBornYear, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(txtCatCode))))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtCatName))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCatColor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(comboCatBreed, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnCatCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCatSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCatEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCatRemove)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtCatCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCatBornYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCatColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboCatHealthStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(comboCatBreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatCreate)
                    .addComponent(btnCatSearch)
                    .addComponent(btnCatEdit)
                    .addComponent(btnCatRemove))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cat Manager", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Go to Veterinaty", jPanel3);

        jLabel8.setText("Code");

        jLabel9.setText("Name");

        jLabel10.setText("Born year ");

        jLabel11.setText("Color");

        jLabel12.setText("Health Status");

        jLabel13.setText("Breed");

        btnDogCreate.setText("Create");
        btnDogCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDogCreateActionPerformed(evt);
            }
        });

        btnDogSearch.setText("Search");
        btnDogSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDogSearchActionPerformed(evt);
            }
        });

        btnDogEdit.setText("Edit");
        btnDogEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDogEditActionPerformed(evt);
            }
        });

        btnDogRemove.setText("Remove");
        btnDogRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDogRemoveActionPerformed(evt);
            }
        });

        txtDogCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDogCodeActionPerformed(evt);
            }
        });

        txtDogName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDogNameActionPerformed(evt);
            }
        });

        comboDogHealthStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Healthy", "Sick", "Item 3", "Item 4" }));

        comboDogBreed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Criollo", "Pastor Aleman", "Item 3", "Item 4" }));

        checkDogPedigree.setText("Pedigree");
        checkDogPedigree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDogPedigreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboDogHealthStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDogCode, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDogBornYear, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(txtDogColor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtDogName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(comboDogBreed, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkDogPedigree)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnDogCreate)
                .addGap(18, 18, 18)
                .addComponent(btnDogSearch)
                .addGap(18, 18, 18)
                .addComponent(btnDogEdit)
                .addGap(18, 18, 18)
                .addComponent(btnDogRemove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtDogCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDogName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(txtDogBornYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDogColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(comboDogHealthStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDogBreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkDogPedigree))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDogCreate)
                    .addComponent(btnDogSearch)
                    .addComponent(btnDogEdit)
                    .addComponent(btnDogRemove))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dog Manager", jPanel4);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Pet Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkDogPedigreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDogPedigreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDogPedigreeActionPerformed

    private void txtDogCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDogCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDogCodeActionPerformed

    private void btnDogEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDogEditActionPerformed
        // TODO add your handling code here:

        String code = txtDogCode.getText();
        boolean found = false;
        clsDog dogg = (clsDog) ctlpet.SearchPet(code, "Perro");
        if (dogg != null){
            ctlpet.EditPet(dogg);
            this.clearDogFields();
            this.FillJlist();
        }
        else{
            JOptionPane.showMessageDialog(this, "Code not found   ");
        }
        
    }//GEN-LAST:event_btnDogEditActionPerformed
    
    private void clearDogFields(){
        txtDogName.setText("");
        txtDogCode.setText("");
        txtDogColor.setText("");
        txtDogBornYear.setText("");
        comboDogBreed.setSelectedIndex(0);
        comboDogHealthStatus.setSelectedIndex(0);
        checkDogPedigree.setSelected(false);
    }
    
    
    private void clearCatFields(){
        txtCatName.setText("");
        txtCatCode.setText("");
        txtCatColor.setText("");
        txtCatBornYear.setText("");
        comboCatBreed.setSelectedIndex(0);
        comboCatHealthStatus.setSelectedIndex(0);
    }
    
    
    
    
    private void btnDogCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDogCreateActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Holi");
       
        
        try {
        String code = txtDogCode.getText();
        String name = txtDogName.getText();
        String color = txtDogColor.getText();
        int bornYear = Integer.parseInt(txtDogBornYear.getText());
        String breed = comboDogBreed.getSelectedItem().toString();
        String healthStatus = comboDogHealthStatus.getSelectedItem().toString();
        boolean pedigree = checkDogPedigree.isSelected();
        if(code.equals("") || name.equals("") || color.equals("")){
            JOptionPane.showMessageDialog(this, "Fill all fields");
        }else{
            clsDog dog = new clsDog(breed, pedigree, code, name, bornYear, color, healthStatus);
            ctlpet.CreatePet(dog);
            dogObjectList.add(dog);
            this.FillJlist();
            this.clearDogFields();
            JOptionPane.showMessageDialog(this, "The record has been saved");
            
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please add a valid born year");
            
        }
    }//GEN-LAST:event_btnDogCreateActionPerformed

    private void btnCatCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatCreateActionPerformed
        // TODO add your handling code here:
        
        try {
        String code = txtCatCode.getText();
        String name = txtCatName.getText();
        String color = txtCatColor.getText();
        int bornYear = Integer.parseInt(txtCatBornYear.getText());
        String breed = comboCatBreed.getSelectedItem().toString();
        String healthStatus = comboCatHealthStatus.getSelectedItem().toString();
        if(code.equals("") || name.equals("") || color.equals("")){
            JOptionPane.showMessageDialog(this, "Fill all fields");
        }else{
            clsCat cat = new clsCat(breed, code, name, bornYear, color, healthStatus);
            catObjectList.add(cat);
            this.FillJlist();
            JOptionPane.showMessageDialog(this, "The record has been saved");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please add a valid born year");
            
        }
    }//GEN-LAST:event_btnCatCreateActionPerformed

    private void txtDogNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDogNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDogNameActionPerformed

    private void btnDogSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDogSearchActionPerformed

        // TODO add your handling code here:

        String code = txtDogCode.getText();
        
        
        clsDog dog = (clsDog) ctlpet.SearchPet(code, "Perro");
        if(dog == null){
            JOptionPane.showMessageDialog(this, "Code not found");
        }else{
                txtDogName.setText(dog.getName());
                txtDogBornYear.setText(dog.getBornYear() + "");
                txtDogColor.setText(dog.getColor());
                comboDogBreed.setSelectedItem(dog.getBreed());
                comboDogHealthStatus.setSelectedItem(dog.getHealthStatus());
                checkDogPedigree.setSelected(dog.isPedigree());
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnDogSearchActionPerformed

    private void btnDogRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDogRemoveActionPerformed
        // TODO add your handling code here:
        String code = txtDogCode.getText();
        try{
        clsDog dog = (clsDog) ctlpet.SearchPet(code, "Perro");
        ctlpet.DeletePet(dog);
        this.clearDogFields();
        this.FillJlist();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Code not found   ");
        }
        
    }//GEN-LAST:event_btnDogRemoveActionPerformed
 
    private void btnCatSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatSearchActionPerformed

    private void btnCatEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatCreate;
    private javax.swing.JButton btnCatEdit;
    private javax.swing.JButton btnCatRemove;
    private javax.swing.JButton btnCatSearch;
    private javax.swing.JButton btnDogCreate;
    private javax.swing.JButton btnDogEdit;
    private javax.swing.JButton btnDogRemove;
    private javax.swing.JButton btnDogSearch;
    private javax.swing.JCheckBox checkDogPedigree;
    private javax.swing.JComboBox<String> comboCatBreed;
    private javax.swing.JComboBox<String> comboCatHealthStatus;
    private javax.swing.JComboBox<String> comboDogBreed;
    private javax.swing.JComboBox<String> comboDogHealthStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JList<String> petList;
    private javax.swing.JTextField txtCatBornYear;
    private javax.swing.JTextField txtCatCode;
    private javax.swing.JTextField txtCatColor;
    private javax.swing.JTextField txtCatName;
    private javax.swing.JTextField txtDogBornYear;
    private javax.swing.JTextField txtDogCode;
    private javax.swing.JTextField txtDogColor;
    private javax.swing.JTextField txtDogName;
    // End of variables declaration//GEN-END:variables
}


